
services:
  users:
    build: ./users
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://user:pass@users-db:5432/users_db
    depends_on:
      - users-db
    volumes:
      - ./users/prisma:/app/prisma

  products:
    build: ./products
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://products_user:products_pass@products-db:5432/products_db
    depends_on:
      - products-db
    volumes:
      - ./products/prisma:/app/prisma

  users-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"

  products-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - users
      - products